"""add catalog models

Revision ID: 1e26b7201aa5
Revises: e501cfa2957a
Create Date: 2026-09-15 12:24:23.604520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e26b7201aa5'
down_revision: Union[str, Sequence[str], None] = 'e501cfa2957a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_categories_name_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('sale_mode', sa.Enum('UNIT', 'WEIGHT', 'FREE_AMOUNT', name='sale_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('price_mode', sa.Enum('FIXED', 'FREE', name='price_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('sale_price_clp', sa.Integer(), nullable=True),
    sa.Column('track_stock', sa.Boolean(), nullable=False),
    sa.Column('track_expiration', sa.Boolean(), nullable=False),
    sa.Column('is_returnable', sa.Boolean(), nullable=False),
    sa.Column('age_restricted', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("price_mode != 'FIXED' OR sale_price_clp IS NOT NULL", name='ck_products_fixed_price_required'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_products_name_not_blank'),
    sa.CheckConstraint('sale_price_clp IS NULL OR sale_price_clp >= 0', name='ck_products_sale_price_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
