"""add payments

Revision ID: 26b39242beaf
Revises: b75e557f5bf2
Create Date: 2026-09-15 20:57:23.061988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b39242beaf'
down_revision: Union[str, Sequence[str], None] = 'b75e557f5bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'CARD', name='payment_method', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED', name='payment_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('amount_clp', sa.Integer(), nullable=False),
    sa.Column('cash_received_clp', sa.Integer(), nullable=True),
    sa.Column('change_clp', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('external_reference', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_clp > 0', name='ck_payments_amount_positive'),
    sa.CheckConstraint('cash_received_clp IS NULL OR cash_received_clp >= 0', name='ck_payments_cash_received_non_negative'),
    sa.CheckConstraint('change_clp IS NULL OR change_clp >= 0', name='ck_payments_change_non_negative'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_method'), 'payments', ['method'], unique=False)
    op.create_index(op.f('ix_payments_sale_id'), 'payments', ['sale_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_sale_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
