"""add sales and sale items

Revision ID: b75e557f5bf2
Revises: c9e5ecb6c715
Create Date: 2026-09-15 20:17:43.707988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75e557f5bf2'
down_revision: Union[str, Sequence[str], None] = 'c9e5ecb6c715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PAYMENT_PENDING', 'COMPLETED', 'CANCELLED', 'VOIDED', name='sale_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('subtotal_clp', sa.Integer(), nullable=False),
    sa.Column('total_clp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('subtotal_clp >= 0', name='ck_sales_subtotal_non_negative'),
    sa.CheckConstraint('total_clp >= 0', name='ck_sales_total_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_created_at'), 'sales', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('item_type', sa.Enum('PRODUCT', 'FREE_AMOUNT', name='sale_item_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description_snapshot', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price_clp', sa.Integer(), nullable=False),
    sa.Column('line_total_clp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(item_type = 'PRODUCT' AND product_id IS NOT NULL) OR (item_type = 'FREE_AMOUNT' AND product_id IS NULL)", name='ck_sale_items_product_reference_by_type'),
    sa.CheckConstraint('length(trim(description_snapshot)) > 0', name='ck_sale_items_description_not_blank'),
    sa.CheckConstraint('line_total_clp >= 0', name='ck_sale_items_line_total_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_sale_items_quantity_positive'),
    sa.CheckConstraint('unit_price_clp >= 0', name='ck_sale_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_created_at'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
