"""add stock movements

Revision ID: c9e5ecb6c715
Revises: 1e26b7201aa5
Create Date: 2026-09-15 20:01:32.218526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e5ecb6c715'
down_revision: Union[str, Sequence[str], None] = '1e26b7201aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.Enum('INITIAL_STOCK', 'PURCHASE', 'SALE', 'SALE_REVERSAL', 'WASTE', 'RETURN', 'ADJUSTMENT', name='stock_movement_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_delta != 0', name='ck_stock_movements_quantity_non_zero'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_actor_user_id'), 'stock_movements', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_stock_movements_product_id"),
        table_name="stock_movements",
    )
    op.drop_index(
        op.f("ix_stock_movements_movement_type"),
        table_name="stock_movements",
    )
    op.drop_index(
        op.f("ix_stock_movements_created_at"),
        table_name="stock_movements",
    )
    op.drop_index(
        op.f("ix_stock_movements_actor_user_id"),
        table_name="stock_movements",
    )
    op.drop_table("stock_movements")